/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BloodBankRouteImport } from './routes/blood-bank'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemberRouteImport } from './routes/member'
import { Route as RetailerRouteImport } from './routes/retailer'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WholesalerRouteImport } from './routes/wholesaler'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminBloodBanksRouteImport } from './routes/admin.blood-banks'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminHospitalsRouteImport } from './routes/admin.hospitals'
import { Route as AdminLabsRouteImport } from './routes/admin.labs'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminRetailersRouteImport } from './routes/admin.retailers'
import { Route as AdminWholesalersRouteImport } from './routes/admin.wholesalers'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as MemberAddressRouteImport } from './routes/member.address'
import { Route as MemberAlertsRouteImport } from './routes/member.alerts'
import { Route as MemberBloodBankRouteImport } from './routes/member.blood-bank'
import { Route as MemberBloodBankAddressRouteImport } from './routes/member.blood-bank-address'
import { Route as MemberBloodDonorsRouteImport } from './routes/member.blood-donors'
import { Route as MemberBloodInventoryRouteImport } from './routes/member.blood-inventory'
import { Route as MemberDirectoryRouteImport } from './routes/member.directory'
import { Route as MemberDoctorRouteImport } from './routes/member.doctor'
import { Route as MemberDoctorHospitalRouteImport } from './routes/member.doctor-hospital'
import { Route as MemberDoctorPatientsRouteImport } from './routes/member.doctor-patients'
import { Route as MemberDocumentsRouteImport } from './routes/member.documents'
import { Route as MemberEmployeesRouteImport } from './routes/member.employees'
import { Route as MemberHospitalRouteImport } from './routes/member.hospital'
import { Route as MemberHospitalAddressRouteImport } from './routes/member.hospital-address'
import { Route as MemberHospitalDoctorsRouteImport } from './routes/member.hospital-doctors'
import { Route as MemberHospitalPatientsRouteImport } from './routes/member.hospital-patients'
import { Route as MemberLabRouteImport } from './routes/member.lab'
import { Route as MemberLabAddressRouteImport } from './routes/member.lab-address'
import { Route as MemberLabServicesRouteImport } from './routes/member.lab-services'
import { Route as MemberLabStaffRouteImport } from './routes/member.lab-staff'
import { Route as MemberLicencesRouteImport } from './routes/member.licences'
import { Route as MemberOwnersRouteImport } from './routes/member.owners'
import { Route as MemberPharmacistsRouteImport } from './routes/member.pharmacists'
import { Route as MemberProfileRouteImport } from './routes/member.profile'
import { Route as MemberRoleDocumentsRouteImport } from './routes/member.role-documents'
import { Route as MemberSettingsRouteImport } from './routes/member.settings'
import { Route as RetailerIndexRouteImport } from './routes/retailer.index'
import { Route as RetailerAlertsRouteImport } from './routes/retailer.alerts'
import { Route as RetailerDirectoryRouteImport } from './routes/retailer.directory'
import { Route as RetailerDocumentsRouteImport } from './routes/retailer.documents'
import { Route as RetailerEmployeesRouteImport } from './routes/retailer.employees'
import { Route as RetailerLicencesRouteImport } from './routes/retailer.licences'
import { Route as RetailerOwnersRouteImport } from './routes/retailer.owners'
import { Route as RetailerPharmacistsRouteImport } from './routes/retailer.pharmacists'
import { Route as RetailerProfileRouteImport } from './routes/retailer.profile'
import { Route as RetailerSettingsRouteImport } from './routes/retailer.settings'
import { Route as RetailersIndexRouteImport } from './routes/retailers.index'
import { Route as RetailersSlugRouteImport } from './routes/retailers.$slug'
import { Route as WholesalerIndexRouteImport } from './routes/wholesaler.index'
import { Route as WholesalerAlertsRouteImport } from './routes/wholesaler.alerts'
import { Route as WholesalerDirectoryRouteImport } from './routes/wholesaler.directory'
import { Route as WholesalerDocumentsRouteImport } from './routes/wholesaler.documents'
import { Route as WholesalerEmployeesRouteImport } from './routes/wholesaler.employees'
import { Route as WholesalerLicencesRouteImport } from './routes/wholesaler.licences'
import { Route as WholesalerOwnersRouteImport } from './routes/wholesaler.owners'
import { Route as WholesalerPharmacistsRouteImport } from './routes/wholesaler.pharmacists'
import { Route as WholesalerProfileRouteImport } from './routes/wholesaler.profile'
import { Route as WholesalerSettingsRouteImport } from './routes/wholesaler.settings'
import { Route as WholesalersIndexRouteImport } from './routes/wholesalers.index'
import { Route as WholesalersSlugRouteImport } from './routes/wholesalers.$slug'
import { Route as AdminFacilitiesSlugRouteImport } from './routes/admin.facilities.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodBankRoute = BloodBankRouteImport.update({
  id: '/blood-bank',
  path: '/blood-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerRoute = RetailerRouteImport.update({
  id: '/retailer',
  path: '/retailer',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesalerRoute = WholesalerRouteImport.update({
  id: '/wholesaler',
  path: '/wholesaler',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBloodBanksRoute = AdminBloodBanksRouteImport.update({
  id: '/blood-banks',
  path: '/blood-banks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHospitalsRoute = AdminHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLabsRoute = AdminLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRetailersRoute = AdminRetailersRouteImport.update({
  id: '/retailers',
  path: '/retailers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWholesalersRoute = AdminWholesalersRouteImport.update({
  id: '/wholesalers',
  path: '/wholesalers',
  getParentRoute: () => AdminRoute,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const MemberAddressRoute = MemberAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => MemberRoute,
} as any)
const MemberAlertsRoute = MemberAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => MemberRoute,
} as any)
const MemberBloodBankRoute = MemberBloodBankRouteImport.update({
  id: '/blood-bank',
  path: '/blood-bank',
  getParentRoute: () => MemberRoute,
} as any)
const MemberBloodBankAddressRoute = MemberBloodBankAddressRouteImport.update({
  id: '/blood-bank-address',
  path: '/blood-bank-address',
  getParentRoute: () => MemberRoute,
} as any)
const MemberBloodDonorsRoute = MemberBloodDonorsRouteImport.update({
  id: '/blood-donors',
  path: '/blood-donors',
  getParentRoute: () => MemberRoute,
} as any)
const MemberBloodInventoryRoute = MemberBloodInventoryRouteImport.update({
  id: '/blood-inventory',
  path: '/blood-inventory',
  getParentRoute: () => MemberRoute,
} as any)
const MemberDirectoryRoute = MemberDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => MemberRoute,
} as any)
const MemberDoctorRoute = MemberDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => MemberRoute,
} as any)
const MemberDoctorHospitalRoute = MemberDoctorHospitalRouteImport.update({
  id: '/doctor-hospital',
  path: '/doctor-hospital',
  getParentRoute: () => MemberRoute,
} as any)
const MemberDoctorPatientsRoute = MemberDoctorPatientsRouteImport.update({
  id: '/doctor-patients',
  path: '/doctor-patients',
  getParentRoute: () => MemberRoute,
} as any)
const MemberDocumentsRoute = MemberDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => MemberRoute,
} as any)
const MemberEmployeesRoute = MemberEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => MemberRoute,
} as any)
const MemberHospitalRoute = MemberHospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => MemberRoute,
} as any)
const MemberHospitalAddressRoute = MemberHospitalAddressRouteImport.update({
  id: '/hospital-address',
  path: '/hospital-address',
  getParentRoute: () => MemberRoute,
} as any)
const MemberHospitalDoctorsRoute = MemberHospitalDoctorsRouteImport.update({
  id: '/hospital-doctors',
  path: '/hospital-doctors',
  getParentRoute: () => MemberRoute,
} as any)
const MemberHospitalPatientsRoute = MemberHospitalPatientsRouteImport.update({
  id: '/hospital-patients',
  path: '/hospital-patients',
  getParentRoute: () => MemberRoute,
} as any)
const MemberLabRoute = MemberLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => MemberRoute,
} as any)
const MemberLabAddressRoute = MemberLabAddressRouteImport.update({
  id: '/lab-address',
  path: '/lab-address',
  getParentRoute: () => MemberRoute,
} as any)
const MemberLabServicesRoute = MemberLabServicesRouteImport.update({
  id: '/lab-services',
  path: '/lab-services',
  getParentRoute: () => MemberRoute,
} as any)
const MemberLabStaffRoute = MemberLabStaffRouteImport.update({
  id: '/lab-staff',
  path: '/lab-staff',
  getParentRoute: () => MemberRoute,
} as any)
const MemberLicencesRoute = MemberLicencesRouteImport.update({
  id: '/licences',
  path: '/licences',
  getParentRoute: () => MemberRoute,
} as any)
const MemberOwnersRoute = MemberOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => MemberRoute,
} as any)
const MemberPharmacistsRoute = MemberPharmacistsRouteImport.update({
  id: '/pharmacists',
  path: '/pharmacists',
  getParentRoute: () => MemberRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberRoleDocumentsRoute = MemberRoleDocumentsRouteImport.update({
  id: '/role-documents',
  path: '/role-documents',
  getParentRoute: () => MemberRoute,
} as any)
const MemberSettingsRoute = MemberSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MemberRoute,
} as any)
const RetailerIndexRoute = RetailerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerAlertsRoute = RetailerAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerDirectoryRoute = RetailerDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerDocumentsRoute = RetailerDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerEmployeesRoute = RetailerEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerLicencesRoute = RetailerLicencesRouteImport.update({
  id: '/licences',
  path: '/licences',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerOwnersRoute = RetailerOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerPharmacistsRoute = RetailerPharmacistsRouteImport.update({
  id: '/pharmacists',
  path: '/pharmacists',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerProfileRoute = RetailerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerSettingsRoute = RetailerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailersIndexRoute = RetailersIndexRouteImport.update({
  id: '/retailers/',
  path: '/retailers/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailersSlugRoute = RetailersSlugRouteImport.update({
  id: '/retailers/$slug',
  path: '/retailers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesalerIndexRoute = WholesalerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WholesalerRoute,
} as any)
const WholesalerAlertsRoute = WholesalerAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => WholesalerRoute,
} as any)
const WholesalerDirectoryRoute = WholesalerDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => WholesalerRoute,
} as any)
const WholesalerDocumentsRoute = WholesalerDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => WholesalerRoute,
} as any)
const WholesalerEmployeesRoute = WholesalerEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => WholesalerRoute,
} as any)
const WholesalerLicencesRoute = WholesalerLicencesRouteImport.update({
  id: '/licences',
  path: '/licences',
  getParentRoute: () => WholesalerRoute,
} as any)
const WholesalerOwnersRoute = WholesalerOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => WholesalerRoute,
} as any)
const WholesalerPharmacistsRoute = WholesalerPharmacistsRouteImport.update({
  id: '/pharmacists',
  path: '/pharmacists',
  getParentRoute: () => WholesalerRoute,
} as any)
const WholesalerProfileRoute = WholesalerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WholesalerRoute,
} as any)
const WholesalerSettingsRoute = WholesalerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WholesalerRoute,
} as any)
const WholesalersIndexRoute = WholesalersIndexRouteImport.update({
  id: '/wholesalers/',
  path: '/wholesalers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesalersSlugRoute = WholesalersSlugRouteImport.update({
  id: '/wholesalers/$slug',
  path: '/wholesalers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacilitiesSlugRoute = AdminFacilitiesSlugRouteImport.update({
  id: '/facilities/$slug',
  path: '/facilities/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blood-bank': typeof BloodBankRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRoute
  '/doctors': typeof DoctorsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hospital': typeof HospitalRoute
  '/hospitals': typeof HospitalsRoute
  '/insurance': typeof InsuranceRoute
  '/join': typeof JoinRoute
  '/lab': typeof LabRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/retailer': typeof RetailerRouteWithChildren
  '/services': typeof ServicesRoute
  '/wholesaler': typeof WholesalerRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/blood-banks': typeof AdminBloodBanksRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/retailers': typeof AdminRetailersRoute
  '/admin/wholesalers': typeof AdminWholesalersRoute
  '/member/address': typeof MemberAddressRoute
  '/member/alerts': typeof MemberAlertsRoute
  '/member/blood-bank': typeof MemberBloodBankRoute
  '/member/blood-bank-address': typeof MemberBloodBankAddressRoute
  '/member/blood-donors': typeof MemberBloodDonorsRoute
  '/member/blood-inventory': typeof MemberBloodInventoryRoute
  '/member/directory': typeof MemberDirectoryRoute
  '/member/doctor': typeof MemberDoctorRoute
  '/member/doctor-hospital': typeof MemberDoctorHospitalRoute
  '/member/doctor-patients': typeof MemberDoctorPatientsRoute
  '/member/documents': typeof MemberDocumentsRoute
  '/member/employees': typeof MemberEmployeesRoute
  '/member/hospital': typeof MemberHospitalRoute
  '/member/hospital-address': typeof MemberHospitalAddressRoute
  '/member/hospital-doctors': typeof MemberHospitalDoctorsRoute
  '/member/hospital-patients': typeof MemberHospitalPatientsRoute
  '/member/lab': typeof MemberLabRoute
  '/member/lab-address': typeof MemberLabAddressRoute
  '/member/lab-services': typeof MemberLabServicesRoute
  '/member/lab-staff': typeof MemberLabStaffRoute
  '/member/licences': typeof MemberLicencesRoute
  '/member/owners': typeof MemberOwnersRoute
  '/member/pharmacists': typeof MemberPharmacistsRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/role-documents': typeof MemberRoleDocumentsRoute
  '/member/settings': typeof MemberSettingsRoute
  '/retailer/alerts': typeof RetailerAlertsRoute
  '/retailer/directory': typeof RetailerDirectoryRoute
  '/retailer/documents': typeof RetailerDocumentsRoute
  '/retailer/employees': typeof RetailerEmployeesRoute
  '/retailer/licences': typeof RetailerLicencesRoute
  '/retailer/owners': typeof RetailerOwnersRoute
  '/retailer/pharmacists': typeof RetailerPharmacistsRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/settings': typeof RetailerSettingsRoute
  '/retailers/$slug': typeof RetailersSlugRoute
  '/wholesaler/alerts': typeof WholesalerAlertsRoute
  '/wholesaler/directory': typeof WholesalerDirectoryRoute
  '/wholesaler/documents': typeof WholesalerDocumentsRoute
  '/wholesaler/employees': typeof WholesalerEmployeesRoute
  '/wholesaler/licences': typeof WholesalerLicencesRoute
  '/wholesaler/owners': typeof WholesalerOwnersRoute
  '/wholesaler/pharmacists': typeof WholesalerPharmacistsRoute
  '/wholesaler/profile': typeof WholesalerProfileRoute
  '/wholesaler/settings': typeof WholesalerSettingsRoute
  '/wholesalers/$slug': typeof WholesalersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
  '/retailer/': typeof RetailerIndexRoute
  '/retailers/': typeof RetailersIndexRoute
  '/wholesaler/': typeof WholesalerIndexRoute
  '/wholesalers/': typeof WholesalersIndexRoute
  '/admin/facilities/$slug': typeof AdminFacilitiesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blood-bank': typeof BloodBankRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRoute
  '/doctors': typeof DoctorsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hospital': typeof HospitalRoute
  '/hospitals': typeof HospitalsRoute
  '/insurance': typeof InsuranceRoute
  '/join': typeof JoinRoute
  '/lab': typeof LabRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/blood-banks': typeof AdminBloodBanksRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/retailers': typeof AdminRetailersRoute
  '/admin/wholesalers': typeof AdminWholesalersRoute
  '/member/address': typeof MemberAddressRoute
  '/member/alerts': typeof MemberAlertsRoute
  '/member/blood-bank': typeof MemberBloodBankRoute
  '/member/blood-bank-address': typeof MemberBloodBankAddressRoute
  '/member/blood-donors': typeof MemberBloodDonorsRoute
  '/member/blood-inventory': typeof MemberBloodInventoryRoute
  '/member/directory': typeof MemberDirectoryRoute
  '/member/doctor': typeof MemberDoctorRoute
  '/member/doctor-hospital': typeof MemberDoctorHospitalRoute
  '/member/doctor-patients': typeof MemberDoctorPatientsRoute
  '/member/documents': typeof MemberDocumentsRoute
  '/member/employees': typeof MemberEmployeesRoute
  '/member/hospital': typeof MemberHospitalRoute
  '/member/hospital-address': typeof MemberHospitalAddressRoute
  '/member/hospital-doctors': typeof MemberHospitalDoctorsRoute
  '/member/hospital-patients': typeof MemberHospitalPatientsRoute
  '/member/lab': typeof MemberLabRoute
  '/member/lab-address': typeof MemberLabAddressRoute
  '/member/lab-services': typeof MemberLabServicesRoute
  '/member/lab-staff': typeof MemberLabStaffRoute
  '/member/licences': typeof MemberLicencesRoute
  '/member/owners': typeof MemberOwnersRoute
  '/member/pharmacists': typeof MemberPharmacistsRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/role-documents': typeof MemberRoleDocumentsRoute
  '/member/settings': typeof MemberSettingsRoute
  '/retailer/alerts': typeof RetailerAlertsRoute
  '/retailer/directory': typeof RetailerDirectoryRoute
  '/retailer/documents': typeof RetailerDocumentsRoute
  '/retailer/employees': typeof RetailerEmployeesRoute
  '/retailer/licences': typeof RetailerLicencesRoute
  '/retailer/owners': typeof RetailerOwnersRoute
  '/retailer/pharmacists': typeof RetailerPharmacistsRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/settings': typeof RetailerSettingsRoute
  '/retailers/$slug': typeof RetailersSlugRoute
  '/wholesaler/alerts': typeof WholesalerAlertsRoute
  '/wholesaler/directory': typeof WholesalerDirectoryRoute
  '/wholesaler/documents': typeof WholesalerDocumentsRoute
  '/wholesaler/employees': typeof WholesalerEmployeesRoute
  '/wholesaler/licences': typeof WholesalerLicencesRoute
  '/wholesaler/owners': typeof WholesalerOwnersRoute
  '/wholesaler/pharmacists': typeof WholesalerPharmacistsRoute
  '/wholesaler/profile': typeof WholesalerProfileRoute
  '/wholesaler/settings': typeof WholesalerSettingsRoute
  '/wholesalers/$slug': typeof WholesalersSlugRoute
  '/admin': typeof AdminIndexRoute
  '/member': typeof MemberIndexRoute
  '/retailer': typeof RetailerIndexRoute
  '/retailers': typeof RetailersIndexRoute
  '/wholesaler': typeof WholesalerIndexRoute
  '/wholesalers': typeof WholesalersIndexRoute
  '/admin/facilities/$slug': typeof AdminFacilitiesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blood-bank': typeof BloodBankRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRoute
  '/doctors': typeof DoctorsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hospital': typeof HospitalRoute
  '/hospitals': typeof HospitalsRoute
  '/insurance': typeof InsuranceRoute
  '/join': typeof JoinRoute
  '/lab': typeof LabRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/retailer': typeof RetailerRouteWithChildren
  '/services': typeof ServicesRoute
  '/wholesaler': typeof WholesalerRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/blood-banks': typeof AdminBloodBanksRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/retailers': typeof AdminRetailersRoute
  '/admin/wholesalers': typeof AdminWholesalersRoute
  '/member/address': typeof MemberAddressRoute
  '/member/alerts': typeof MemberAlertsRoute
  '/member/blood-bank': typeof MemberBloodBankRoute
  '/member/blood-bank-address': typeof MemberBloodBankAddressRoute
  '/member/blood-donors': typeof MemberBloodDonorsRoute
  '/member/blood-inventory': typeof MemberBloodInventoryRoute
  '/member/directory': typeof MemberDirectoryRoute
  '/member/doctor': typeof MemberDoctorRoute
  '/member/doctor-hospital': typeof MemberDoctorHospitalRoute
  '/member/doctor-patients': typeof MemberDoctorPatientsRoute
  '/member/documents': typeof MemberDocumentsRoute
  '/member/employees': typeof MemberEmployeesRoute
  '/member/hospital': typeof MemberHospitalRoute
  '/member/hospital-address': typeof MemberHospitalAddressRoute
  '/member/hospital-doctors': typeof MemberHospitalDoctorsRoute
  '/member/hospital-patients': typeof MemberHospitalPatientsRoute
  '/member/lab': typeof MemberLabRoute
  '/member/lab-address': typeof MemberLabAddressRoute
  '/member/lab-services': typeof MemberLabServicesRoute
  '/member/lab-staff': typeof MemberLabStaffRoute
  '/member/licences': typeof MemberLicencesRoute
  '/member/owners': typeof MemberOwnersRoute
  '/member/pharmacists': typeof MemberPharmacistsRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/role-documents': typeof MemberRoleDocumentsRoute
  '/member/settings': typeof MemberSettingsRoute
  '/retailer/alerts': typeof RetailerAlertsRoute
  '/retailer/directory': typeof RetailerDirectoryRoute
  '/retailer/documents': typeof RetailerDocumentsRoute
  '/retailer/employees': typeof RetailerEmployeesRoute
  '/retailer/licences': typeof RetailerLicencesRoute
  '/retailer/owners': typeof RetailerOwnersRoute
  '/retailer/pharmacists': typeof RetailerPharmacistsRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/settings': typeof RetailerSettingsRoute
  '/retailers/$slug': typeof RetailersSlugRoute
  '/wholesaler/alerts': typeof WholesalerAlertsRoute
  '/wholesaler/directory': typeof WholesalerDirectoryRoute
  '/wholesaler/documents': typeof WholesalerDocumentsRoute
  '/wholesaler/employees': typeof WholesalerEmployeesRoute
  '/wholesaler/licences': typeof WholesalerLicencesRoute
  '/wholesaler/owners': typeof WholesalerOwnersRoute
  '/wholesaler/pharmacists': typeof WholesalerPharmacistsRoute
  '/wholesaler/profile': typeof WholesalerProfileRoute
  '/wholesaler/settings': typeof WholesalerSettingsRoute
  '/wholesalers/$slug': typeof WholesalersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
  '/retailer/': typeof RetailerIndexRoute
  '/retailers/': typeof RetailersIndexRoute
  '/wholesaler/': typeof WholesalerIndexRoute
  '/wholesalers/': typeof WholesalersIndexRoute
  '/admin/facilities/$slug': typeof AdminFacilitiesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blood-bank'
    | '/career'
    | '/contact'
    | '/doctor'
    | '/doctors'
    | '/forgot-password'
    | '/hospital'
    | '/hospitals'
    | '/insurance'
    | '/join'
    | '/lab'
    | '/labs'
    | '/login'
    | '/member'
    | '/retailer'
    | '/services'
    | '/wholesaler'
    | '/admin/approvals'
    | '/admin/blood-banks'
    | '/admin/doctors'
    | '/admin/hospitals'
    | '/admin/labs'
    | '/admin/overview'
    | '/admin/retailers'
    | '/admin/wholesalers'
    | '/member/address'
    | '/member/alerts'
    | '/member/blood-bank'
    | '/member/blood-bank-address'
    | '/member/blood-donors'
    | '/member/blood-inventory'
    | '/member/directory'
    | '/member/doctor'
    | '/member/doctor-hospital'
    | '/member/doctor-patients'
    | '/member/documents'
    | '/member/employees'
    | '/member/hospital'
    | '/member/hospital-address'
    | '/member/hospital-doctors'
    | '/member/hospital-patients'
    | '/member/lab'
    | '/member/lab-address'
    | '/member/lab-services'
    | '/member/lab-staff'
    | '/member/licences'
    | '/member/owners'
    | '/member/pharmacists'
    | '/member/profile'
    | '/member/role-documents'
    | '/member/settings'
    | '/retailer/alerts'
    | '/retailer/directory'
    | '/retailer/documents'
    | '/retailer/employees'
    | '/retailer/licences'
    | '/retailer/owners'
    | '/retailer/pharmacists'
    | '/retailer/profile'
    | '/retailer/settings'
    | '/retailers/$slug'
    | '/wholesaler/alerts'
    | '/wholesaler/directory'
    | '/wholesaler/documents'
    | '/wholesaler/employees'
    | '/wholesaler/licences'
    | '/wholesaler/owners'
    | '/wholesaler/pharmacists'
    | '/wholesaler/profile'
    | '/wholesaler/settings'
    | '/wholesalers/$slug'
    | '/admin/'
    | '/member/'
    | '/retailer/'
    | '/retailers/'
    | '/wholesaler/'
    | '/wholesalers/'
    | '/admin/facilities/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blood-bank'
    | '/career'
    | '/contact'
    | '/doctor'
    | '/doctors'
    | '/forgot-password'
    | '/hospital'
    | '/hospitals'
    | '/insurance'
    | '/join'
    | '/lab'
    | '/labs'
    | '/login'
    | '/services'
    | '/admin/approvals'
    | '/admin/blood-banks'
    | '/admin/doctors'
    | '/admin/hospitals'
    | '/admin/labs'
    | '/admin/overview'
    | '/admin/retailers'
    | '/admin/wholesalers'
    | '/member/address'
    | '/member/alerts'
    | '/member/blood-bank'
    | '/member/blood-bank-address'
    | '/member/blood-donors'
    | '/member/blood-inventory'
    | '/member/directory'
    | '/member/doctor'
    | '/member/doctor-hospital'
    | '/member/doctor-patients'
    | '/member/documents'
    | '/member/employees'
    | '/member/hospital'
    | '/member/hospital-address'
    | '/member/hospital-doctors'
    | '/member/hospital-patients'
    | '/member/lab'
    | '/member/lab-address'
    | '/member/lab-services'
    | '/member/lab-staff'
    | '/member/licences'
    | '/member/owners'
    | '/member/pharmacists'
    | '/member/profile'
    | '/member/role-documents'
    | '/member/settings'
    | '/retailer/alerts'
    | '/retailer/directory'
    | '/retailer/documents'
    | '/retailer/employees'
    | '/retailer/licences'
    | '/retailer/owners'
    | '/retailer/pharmacists'
    | '/retailer/profile'
    | '/retailer/settings'
    | '/retailers/$slug'
    | '/wholesaler/alerts'
    | '/wholesaler/directory'
    | '/wholesaler/documents'
    | '/wholesaler/employees'
    | '/wholesaler/licences'
    | '/wholesaler/owners'
    | '/wholesaler/pharmacists'
    | '/wholesaler/profile'
    | '/wholesaler/settings'
    | '/wholesalers/$slug'
    | '/admin'
    | '/member'
    | '/retailer'
    | '/retailers'
    | '/wholesaler'
    | '/wholesalers'
    | '/admin/facilities/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blood-bank'
    | '/career'
    | '/contact'
    | '/doctor'
    | '/doctors'
    | '/forgot-password'
    | '/hospital'
    | '/hospitals'
    | '/insurance'
    | '/join'
    | '/lab'
    | '/labs'
    | '/login'
    | '/member'
    | '/retailer'
    | '/services'
    | '/wholesaler'
    | '/admin/approvals'
    | '/admin/blood-banks'
    | '/admin/doctors'
    | '/admin/hospitals'
    | '/admin/labs'
    | '/admin/overview'
    | '/admin/retailers'
    | '/admin/wholesalers'
    | '/member/address'
    | '/member/alerts'
    | '/member/blood-bank'
    | '/member/blood-bank-address'
    | '/member/blood-donors'
    | '/member/blood-inventory'
    | '/member/directory'
    | '/member/doctor'
    | '/member/doctor-hospital'
    | '/member/doctor-patients'
    | '/member/documents'
    | '/member/employees'
    | '/member/hospital'
    | '/member/hospital-address'
    | '/member/hospital-doctors'
    | '/member/hospital-patients'
    | '/member/lab'
    | '/member/lab-address'
    | '/member/lab-services'
    | '/member/lab-staff'
    | '/member/licences'
    | '/member/owners'
    | '/member/pharmacists'
    | '/member/profile'
    | '/member/role-documents'
    | '/member/settings'
    | '/retailer/alerts'
    | '/retailer/directory'
    | '/retailer/documents'
    | '/retailer/employees'
    | '/retailer/licences'
    | '/retailer/owners'
    | '/retailer/pharmacists'
    | '/retailer/profile'
    | '/retailer/settings'
    | '/retailers/$slug'
    | '/wholesaler/alerts'
    | '/wholesaler/directory'
    | '/wholesaler/documents'
    | '/wholesaler/employees'
    | '/wholesaler/licences'
    | '/wholesaler/owners'
    | '/wholesaler/pharmacists'
    | '/wholesaler/profile'
    | '/wholesaler/settings'
    | '/wholesalers/$slug'
    | '/admin/'
    | '/member/'
    | '/retailer/'
    | '/retailers/'
    | '/wholesaler/'
    | '/wholesalers/'
    | '/admin/facilities/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BloodBankRoute: typeof BloodBankRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  DoctorRoute: typeof DoctorRoute
  DoctorsRoute: typeof DoctorsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HospitalRoute: typeof HospitalRoute
  HospitalsRoute: typeof HospitalsRoute
  InsuranceRoute: typeof InsuranceRoute
  JoinRoute: typeof JoinRoute
  LabRoute: typeof LabRoute
  LabsRoute: typeof LabsRoute
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRouteWithChildren
  RetailerRoute: typeof RetailerRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  WholesalerRoute: typeof WholesalerRouteWithChildren
  RetailersSlugRoute: typeof RetailersSlugRoute
  WholesalersSlugRoute: typeof WholesalersSlugRoute
  RetailersIndexRoute: typeof RetailersIndexRoute
  WholesalersIndexRoute: typeof WholesalersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blood-bank': {
      id: '/blood-bank'
      path: '/blood-bank'
      fullPath: '/blood-bank'
      preLoaderRoute: typeof BloodBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer': {
      id: '/retailer'
      path: '/retailer'
      fullPath: '/retailer'
      preLoaderRoute: typeof RetailerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesaler': {
      id: '/wholesaler'
      path: '/wholesaler'
      fullPath: '/wholesaler'
      preLoaderRoute: typeof WholesalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blood-banks': {
      id: '/admin/blood-banks'
      path: '/blood-banks'
      fullPath: '/admin/blood-banks'
      preLoaderRoute: typeof AdminBloodBanksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hospitals': {
      id: '/admin/hospitals'
      path: '/hospitals'
      fullPath: '/admin/hospitals'
      preLoaderRoute: typeof AdminHospitalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/labs': {
      id: '/admin/labs'
      path: '/labs'
      fullPath: '/admin/labs'
      preLoaderRoute: typeof AdminLabsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/retailers': {
      id: '/admin/retailers'
      path: '/retailers'
      fullPath: '/admin/retailers'
      preLoaderRoute: typeof AdminRetailersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wholesalers': {
      id: '/admin/wholesalers'
      path: '/wholesalers'
      fullPath: '/admin/wholesalers'
      preLoaderRoute: typeof AdminWholesalersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/address': {
      id: '/member/address'
      path: '/address'
      fullPath: '/member/address'
      preLoaderRoute: typeof MemberAddressRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/alerts': {
      id: '/member/alerts'
      path: '/alerts'
      fullPath: '/member/alerts'
      preLoaderRoute: typeof MemberAlertsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/blood-bank': {
      id: '/member/blood-bank'
      path: '/blood-bank'
      fullPath: '/member/blood-bank'
      preLoaderRoute: typeof MemberBloodBankRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/blood-bank-address': {
      id: '/member/blood-bank-address'
      path: '/blood-bank-address'
      fullPath: '/member/blood-bank-address'
      preLoaderRoute: typeof MemberBloodBankAddressRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/blood-donors': {
      id: '/member/blood-donors'
      path: '/blood-donors'
      fullPath: '/member/blood-donors'
      preLoaderRoute: typeof MemberBloodDonorsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/blood-inventory': {
      id: '/member/blood-inventory'
      path: '/blood-inventory'
      fullPath: '/member/blood-inventory'
      preLoaderRoute: typeof MemberBloodInventoryRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/directory': {
      id: '/member/directory'
      path: '/directory'
      fullPath: '/member/directory'
      preLoaderRoute: typeof MemberDirectoryRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/doctor': {
      id: '/member/doctor'
      path: '/doctor'
      fullPath: '/member/doctor'
      preLoaderRoute: typeof MemberDoctorRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/doctor-hospital': {
      id: '/member/doctor-hospital'
      path: '/doctor-hospital'
      fullPath: '/member/doctor-hospital'
      preLoaderRoute: typeof MemberDoctorHospitalRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/doctor-patients': {
      id: '/member/doctor-patients'
      path: '/doctor-patients'
      fullPath: '/member/doctor-patients'
      preLoaderRoute: typeof MemberDoctorPatientsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/documents': {
      id: '/member/documents'
      path: '/documents'
      fullPath: '/member/documents'
      preLoaderRoute: typeof MemberDocumentsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/employees': {
      id: '/member/employees'
      path: '/employees'
      fullPath: '/member/employees'
      preLoaderRoute: typeof MemberEmployeesRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/hospital': {
      id: '/member/hospital'
      path: '/hospital'
      fullPath: '/member/hospital'
      preLoaderRoute: typeof MemberHospitalRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/hospital-address': {
      id: '/member/hospital-address'
      path: '/hospital-address'
      fullPath: '/member/hospital-address'
      preLoaderRoute: typeof MemberHospitalAddressRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/hospital-doctors': {
      id: '/member/hospital-doctors'
      path: '/hospital-doctors'
      fullPath: '/member/hospital-doctors'
      preLoaderRoute: typeof MemberHospitalDoctorsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/hospital-patients': {
      id: '/member/hospital-patients'
      path: '/hospital-patients'
      fullPath: '/member/hospital-patients'
      preLoaderRoute: typeof MemberHospitalPatientsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/lab': {
      id: '/member/lab'
      path: '/lab'
      fullPath: '/member/lab'
      preLoaderRoute: typeof MemberLabRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/lab-address': {
      id: '/member/lab-address'
      path: '/lab-address'
      fullPath: '/member/lab-address'
      preLoaderRoute: typeof MemberLabAddressRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/lab-services': {
      id: '/member/lab-services'
      path: '/lab-services'
      fullPath: '/member/lab-services'
      preLoaderRoute: typeof MemberLabServicesRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/lab-staff': {
      id: '/member/lab-staff'
      path: '/lab-staff'
      fullPath: '/member/lab-staff'
      preLoaderRoute: typeof MemberLabStaffRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/licences': {
      id: '/member/licences'
      path: '/licences'
      fullPath: '/member/licences'
      preLoaderRoute: typeof MemberLicencesRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/owners': {
      id: '/member/owners'
      path: '/owners'
      fullPath: '/member/owners'
      preLoaderRoute: typeof MemberOwnersRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/pharmacists': {
      id: '/member/pharmacists'
      path: '/pharmacists'
      fullPath: '/member/pharmacists'
      preLoaderRoute: typeof MemberPharmacistsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/role-documents': {
      id: '/member/role-documents'
      path: '/role-documents'
      fullPath: '/member/role-documents'
      preLoaderRoute: typeof MemberRoleDocumentsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/settings': {
      id: '/member/settings'
      path: '/settings'
      fullPath: '/member/settings'
      preLoaderRoute: typeof MemberSettingsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/retailer/': {
      id: '/retailer/'
      path: '/'
      fullPath: '/retailer/'
      preLoaderRoute: typeof RetailerIndexRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/alerts': {
      id: '/retailer/alerts'
      path: '/alerts'
      fullPath: '/retailer/alerts'
      preLoaderRoute: typeof RetailerAlertsRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/directory': {
      id: '/retailer/directory'
      path: '/directory'
      fullPath: '/retailer/directory'
      preLoaderRoute: typeof RetailerDirectoryRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/documents': {
      id: '/retailer/documents'
      path: '/documents'
      fullPath: '/retailer/documents'
      preLoaderRoute: typeof RetailerDocumentsRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/employees': {
      id: '/retailer/employees'
      path: '/employees'
      fullPath: '/retailer/employees'
      preLoaderRoute: typeof RetailerEmployeesRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/licences': {
      id: '/retailer/licences'
      path: '/licences'
      fullPath: '/retailer/licences'
      preLoaderRoute: typeof RetailerLicencesRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/owners': {
      id: '/retailer/owners'
      path: '/owners'
      fullPath: '/retailer/owners'
      preLoaderRoute: typeof RetailerOwnersRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/pharmacists': {
      id: '/retailer/pharmacists'
      path: '/pharmacists'
      fullPath: '/retailer/pharmacists'
      preLoaderRoute: typeof RetailerPharmacistsRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/profile': {
      id: '/retailer/profile'
      path: '/profile'
      fullPath: '/retailer/profile'
      preLoaderRoute: typeof RetailerProfileRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/settings': {
      id: '/retailer/settings'
      path: '/settings'
      fullPath: '/retailer/settings'
      preLoaderRoute: typeof RetailerSettingsRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailers/': {
      id: '/retailers/'
      path: '/retailers'
      fullPath: '/retailers/'
      preLoaderRoute: typeof RetailersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailers/$slug': {
      id: '/retailers/$slug'
      path: '/retailers/$slug'
      fullPath: '/retailers/$slug'
      preLoaderRoute: typeof RetailersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesaler/': {
      id: '/wholesaler/'
      path: '/'
      fullPath: '/wholesaler/'
      preLoaderRoute: typeof WholesalerIndexRouteImport
      parentRoute: typeof WholesalerRoute
    }
    '/wholesaler/alerts': {
      id: '/wholesaler/alerts'
      path: '/alerts'
      fullPath: '/wholesaler/alerts'
      preLoaderRoute: typeof WholesalerAlertsRouteImport
      parentRoute: typeof WholesalerRoute
    }
    '/wholesaler/directory': {
      id: '/wholesaler/directory'
      path: '/directory'
      fullPath: '/wholesaler/directory'
      preLoaderRoute: typeof WholesalerDirectoryRouteImport
      parentRoute: typeof WholesalerRoute
    }
    '/wholesaler/documents': {
      id: '/wholesaler/documents'
      path: '/documents'
      fullPath: '/wholesaler/documents'
      preLoaderRoute: typeof WholesalerDocumentsRouteImport
      parentRoute: typeof WholesalerRoute
    }
    '/wholesaler/employees': {
      id: '/wholesaler/employees'
      path: '/employees'
      fullPath: '/wholesaler/employees'
      preLoaderRoute: typeof WholesalerEmployeesRouteImport
      parentRoute: typeof WholesalerRoute
    }
    '/wholesaler/licences': {
      id: '/wholesaler/licences'
      path: '/licences'
      fullPath: '/wholesaler/licences'
      preLoaderRoute: typeof WholesalerLicencesRouteImport
      parentRoute: typeof WholesalerRoute
    }
    '/wholesaler/owners': {
      id: '/wholesaler/owners'
      path: '/owners'
      fullPath: '/wholesaler/owners'
      preLoaderRoute: typeof WholesalerOwnersRouteImport
      parentRoute: typeof WholesalerRoute
    }
    '/wholesaler/pharmacists': {
      id: '/wholesaler/pharmacists'
      path: '/pharmacists'
      fullPath: '/wholesaler/pharmacists'
      preLoaderRoute: typeof WholesalerPharmacistsRouteImport
      parentRoute: typeof WholesalerRoute
    }
    '/wholesaler/profile': {
      id: '/wholesaler/profile'
      path: '/profile'
      fullPath: '/wholesaler/profile'
      preLoaderRoute: typeof WholesalerProfileRouteImport
      parentRoute: typeof WholesalerRoute
    }
    '/wholesaler/settings': {
      id: '/wholesaler/settings'
      path: '/settings'
      fullPath: '/wholesaler/settings'
      preLoaderRoute: typeof WholesalerSettingsRouteImport
      parentRoute: typeof WholesalerRoute
    }
    '/wholesalers/': {
      id: '/wholesalers/'
      path: '/wholesalers'
      fullPath: '/wholesalers/'
      preLoaderRoute: typeof WholesalersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesalers/$slug': {
      id: '/wholesalers/$slug'
      path: '/wholesalers/$slug'
      fullPath: '/wholesalers/$slug'
      preLoaderRoute: typeof WholesalersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/facilities/$slug': {
      id: '/admin/facilities/$slug'
      path: '/facilities/$slug'
      fullPath: '/admin/facilities/$slug'
      preLoaderRoute: typeof AdminFacilitiesSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminBloodBanksRoute: typeof AdminBloodBanksRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminHospitalsRoute: typeof AdminHospitalsRoute
  AdminLabsRoute: typeof AdminLabsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminRetailersRoute: typeof AdminRetailersRoute
  AdminWholesalersRoute: typeof AdminWholesalersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFacilitiesSlugRoute: typeof AdminFacilitiesSlugRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminBloodBanksRoute: AdminBloodBanksRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminHospitalsRoute: AdminHospitalsRoute,
  AdminLabsRoute: AdminLabsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminRetailersRoute: AdminRetailersRoute,
  AdminWholesalersRoute: AdminWholesalersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFacilitiesSlugRoute: AdminFacilitiesSlugRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MemberRouteChildren {
  MemberAddressRoute: typeof MemberAddressRoute
  MemberAlertsRoute: typeof MemberAlertsRoute
  MemberBloodBankRoute: typeof MemberBloodBankRoute
  MemberBloodBankAddressRoute: typeof MemberBloodBankAddressRoute
  MemberBloodDonorsRoute: typeof MemberBloodDonorsRoute
  MemberBloodInventoryRoute: typeof MemberBloodInventoryRoute
  MemberDirectoryRoute: typeof MemberDirectoryRoute
  MemberDoctorRoute: typeof MemberDoctorRoute
  MemberDoctorHospitalRoute: typeof MemberDoctorHospitalRoute
  MemberDoctorPatientsRoute: typeof MemberDoctorPatientsRoute
  MemberDocumentsRoute: typeof MemberDocumentsRoute
  MemberEmployeesRoute: typeof MemberEmployeesRoute
  MemberHospitalRoute: typeof MemberHospitalRoute
  MemberHospitalAddressRoute: typeof MemberHospitalAddressRoute
  MemberHospitalDoctorsRoute: typeof MemberHospitalDoctorsRoute
  MemberHospitalPatientsRoute: typeof MemberHospitalPatientsRoute
  MemberLabRoute: typeof MemberLabRoute
  MemberLabAddressRoute: typeof MemberLabAddressRoute
  MemberLabServicesRoute: typeof MemberLabServicesRoute
  MemberLabStaffRoute: typeof MemberLabStaffRoute
  MemberLicencesRoute: typeof MemberLicencesRoute
  MemberOwnersRoute: typeof MemberOwnersRoute
  MemberPharmacistsRoute: typeof MemberPharmacistsRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberRoleDocumentsRoute: typeof MemberRoleDocumentsRoute
  MemberSettingsRoute: typeof MemberSettingsRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberAddressRoute: MemberAddressRoute,
  MemberAlertsRoute: MemberAlertsRoute,
  MemberBloodBankRoute: MemberBloodBankRoute,
  MemberBloodBankAddressRoute: MemberBloodBankAddressRoute,
  MemberBloodDonorsRoute: MemberBloodDonorsRoute,
  MemberBloodInventoryRoute: MemberBloodInventoryRoute,
  MemberDirectoryRoute: MemberDirectoryRoute,
  MemberDoctorRoute: MemberDoctorRoute,
  MemberDoctorHospitalRoute: MemberDoctorHospitalRoute,
  MemberDoctorPatientsRoute: MemberDoctorPatientsRoute,
  MemberDocumentsRoute: MemberDocumentsRoute,
  MemberEmployeesRoute: MemberEmployeesRoute,
  MemberHospitalRoute: MemberHospitalRoute,
  MemberHospitalAddressRoute: MemberHospitalAddressRoute,
  MemberHospitalDoctorsRoute: MemberHospitalDoctorsRoute,
  MemberHospitalPatientsRoute: MemberHospitalPatientsRoute,
  MemberLabRoute: MemberLabRoute,
  MemberLabAddressRoute: MemberLabAddressRoute,
  MemberLabServicesRoute: MemberLabServicesRoute,
  MemberLabStaffRoute: MemberLabStaffRoute,
  MemberLicencesRoute: MemberLicencesRoute,
  MemberOwnersRoute: MemberOwnersRoute,
  MemberPharmacistsRoute: MemberPharmacistsRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberRoleDocumentsRoute: MemberRoleDocumentsRoute,
  MemberSettingsRoute: MemberSettingsRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface RetailerRouteChildren {
  RetailerAlertsRoute: typeof RetailerAlertsRoute
  RetailerDirectoryRoute: typeof RetailerDirectoryRoute
  RetailerDocumentsRoute: typeof RetailerDocumentsRoute
  RetailerEmployeesRoute: typeof RetailerEmployeesRoute
  RetailerLicencesRoute: typeof RetailerLicencesRoute
  RetailerOwnersRoute: typeof RetailerOwnersRoute
  RetailerPharmacistsRoute: typeof RetailerPharmacistsRoute
  RetailerProfileRoute: typeof RetailerProfileRoute
  RetailerSettingsRoute: typeof RetailerSettingsRoute
  RetailerIndexRoute: typeof RetailerIndexRoute
}

const RetailerRouteChildren: RetailerRouteChildren = {
  RetailerAlertsRoute: RetailerAlertsRoute,
  RetailerDirectoryRoute: RetailerDirectoryRoute,
  RetailerDocumentsRoute: RetailerDocumentsRoute,
  RetailerEmployeesRoute: RetailerEmployeesRoute,
  RetailerLicencesRoute: RetailerLicencesRoute,
  RetailerOwnersRoute: RetailerOwnersRoute,
  RetailerPharmacistsRoute: RetailerPharmacistsRoute,
  RetailerProfileRoute: RetailerProfileRoute,
  RetailerSettingsRoute: RetailerSettingsRoute,
  RetailerIndexRoute: RetailerIndexRoute,
}

const RetailerRouteWithChildren = RetailerRoute._addFileChildren(
  RetailerRouteChildren,
)

interface WholesalerRouteChildren {
  WholesalerAlertsRoute: typeof WholesalerAlertsRoute
  WholesalerDirectoryRoute: typeof WholesalerDirectoryRoute
  WholesalerDocumentsRoute: typeof WholesalerDocumentsRoute
  WholesalerEmployeesRoute: typeof WholesalerEmployeesRoute
  WholesalerLicencesRoute: typeof WholesalerLicencesRoute
  WholesalerOwnersRoute: typeof WholesalerOwnersRoute
  WholesalerPharmacistsRoute: typeof WholesalerPharmacistsRoute
  WholesalerProfileRoute: typeof WholesalerProfileRoute
  WholesalerSettingsRoute: typeof WholesalerSettingsRoute
  WholesalerIndexRoute: typeof WholesalerIndexRoute
}

const WholesalerRouteChildren: WholesalerRouteChildren = {
  WholesalerAlertsRoute: WholesalerAlertsRoute,
  WholesalerDirectoryRoute: WholesalerDirectoryRoute,
  WholesalerDocumentsRoute: WholesalerDocumentsRoute,
  WholesalerEmployeesRoute: WholesalerEmployeesRoute,
  WholesalerLicencesRoute: WholesalerLicencesRoute,
  WholesalerOwnersRoute: WholesalerOwnersRoute,
  WholesalerPharmacistsRoute: WholesalerPharmacistsRoute,
  WholesalerProfileRoute: WholesalerProfileRoute,
  WholesalerSettingsRoute: WholesalerSettingsRoute,
  WholesalerIndexRoute: WholesalerIndexRoute,
}

const WholesalerRouteWithChildren = WholesalerRoute._addFileChildren(
  WholesalerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BloodBankRoute: BloodBankRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  DoctorRoute: DoctorRoute,
  DoctorsRoute: DoctorsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HospitalRoute: HospitalRoute,
  HospitalsRoute: HospitalsRoute,
  InsuranceRoute: InsuranceRoute,
  JoinRoute: JoinRoute,
  LabRoute: LabRoute,
  LabsRoute: LabsRoute,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRouteWithChildren,
  RetailerRoute: RetailerRouteWithChildren,
  ServicesRoute: ServicesRoute,
  WholesalerRoute: WholesalerRouteWithChildren,
  RetailersSlugRoute: RetailersSlugRoute,
  WholesalersSlugRoute: WholesalersSlugRoute,
  RetailersIndexRoute: RetailersIndexRoute,
  WholesalersIndexRoute: WholesalersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
